import Head from "next/head";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useState } from "preact/hooks";
import { useRouter } from "next/navigation";
import { setCookie } from "nookies";
import { api } from "@/pages/api/api";
import Image from "next/image";

export default function CriarConta() {
  const [form, setForm] = useState({ email: "", senha: "", nome: "" });
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  async function criarConta(event) {
    event.preventDefault();
    try {
      setLoading(true);
      const response = await api.post("/usuario", form);
      const { nome } = response.data.content;

      alert(
        `${nome} sua conta criada com sucesso! Você será redirecionado para o login.`
      );
      setLoading(false);
      router.push("/login", { scroll: false });
    } catch (err) {
      setLoading(false);
      alert(err.response.data.error);
    }
  }

  function onChange(event) {
    const { name, value } = event.target;
    setForm({ ...form, [name]: value });
  }
  return (
    <>
      <Head>
        <title>BancaFácil</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
          <div className="sm:mx-auto sm:w-full sm:max-w-sm text-center align-middle items-center flex flex-col">
            <Image src="/logov1.png" width={250} height={250} alt="logo" className="se" />

            <h2 className="mt-3 leading-9 tracking-tight text-lg">Criar conta</h2>
          </div>

          <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
            <form className="space-y-6" onSubmit={criarConta}>
              <div>
                <div className="flex items-center justify-between">
                  <label
                    htmlFor="password"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Nome
                  </label>
                </div>
                <div className="mt-2">
                  <input
                    id="nome"
                    name="nome"
                    type="text"
                    required
                    onChange={onChange}
                    className="block w-full rounded-md border-0 p-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>
              <div>
                <label
                  htmlFor="email"
                  className="block text-sm font-medium leading-6 text-gray-900"
                >
                  Email
                </label>
                <div className="mt-2">
                  <input
                    id="email"
                    name="email"
                    type="email"
                    onChange={onChange}
                    autoComplete="email"
                    required
                    className="block w-full rounded-md border-0 p-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between">
                  <label
                    htmlFor="password"
                    className="block text-sm font-medium leading-6 text-gray-900"
                  >
                    Senha
                  </label>
                  <div className="text-sm hidden">
                    <a
                      href="#"
                      className="font-semibold text-indigo-600 hover:text-indigo-500"
                    >
                      Forgot password?
                    </a>
                  </div>
                </div>
                <div className="mt-2">
                  <input
                    id="password"
                    name="senha"
                    type="password"
                    autoComplete="current-password"
                    required
                    onChange={onChange}
                    className="block w-full rounded-md border-0 p-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>

              <div>
                <button
                  type="submit"
                  className="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >
                  {loading ? (
                    <svg
                      class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        class="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        stroke-width="4"
                      ></circle>
                      <path
                        class="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      ></path>
                    </svg>
                  ) : (
                    "CRIAR"
                  )}
                </button>
              </div>
            </form>
            <span className="text-gray-500 font-medium text-center block my-3 ">
              Já tem uma conta?{" "}
              <Link className="font-bold text-[#4F46E5]" href="/login">
                ENTRE
              </Link>
            </span>
          </div>
        </div>{" "}
      </main>
    </>
  );
}
